---
bibliography: references.bib
---

## Group Member Accomplishments

*Roland Abi*

Developed the research question for the classification, and found the data set for `california health professional shortage area` and cleaned and transformed the data. Completed logistic regression model (full and reduced), as well as cross validation approaches contributed to completing decision tree and boosting models, carried out 627 tasks for model selection and two wrote the classification section of the summary as well as future direction.   

*Elise Buellesbach*

Found and proposed the original CA data set (`California Hospital Inpatient Mortality Rates and Quality Ratings`). Completed the linear regression models (both full and reduced). Wrote the executive summary, summary/conclusion, ethical analysis, and references. 

*Amanda Concepcion*



*Spencer Grewe*

Organized report and repository. Acquired CA demographic data (`data4`). Contributed toward cleaning, tidying and joining data sets 1, 3, and 4 for the regression tasks. Made and summarized regression models 2 and 3, and carried out 627 tasks involving cross-validation, model selection, and survey of multicollinearity.


## Statement of Data Availability

The source code, data, and full supporting information are available at the [shared repository](https://github.com/sbgrewe/STAT627-FinalProj), which will be made public on the date of the submission of this report. We declare that all authors equally own the contents of the repository. 


{{< pagebreak >}}

## Bibliography

- Asch, David A., Md Nazmul Islam, Natalie E. Sheils, Yong Chen, Jalpa A. Doshi, John Buresh, and Rachel M. Werner. 2021. “Patient and Hospital Factors Associated with Differences in Mortality Rates among Black and White US Medicare Beneficiaries Hospitalized with COVID-19 Infection.” JAMA Network Open 4 (6): e2112842. https://doi.org/10.1001/jamanetworkopen.2021.12842.

- California Open Data Portal. “California Hospital Inpatient Mortality Rates and Quality Ratings,” August 10, 2023. https://data.ca.gov/dataset/california-hospital-inpatient-mortality-rates-and-quality-ratings.

- California Open Data Portal. “Primary Care HPSAs,” March 28, 2024. https://data.ca.gov/dataset/health-professional-shortage-areas-in-california/resource/194e0874-7619-4d70-9198-47943ac17089.

- datausa.io. “California | Data USA,” n.d. https://datausa.io/profile/geo/california?compare=united-states.

- English, Mike, Paul Mwaniki, Thomas Julius, Mercy Chepkirui, David Gathara, Paul O. Ouma, Peter Cherutich, Emelda A. Okiro, and Robert W. Snow. 2018. “Hospital Mortality – a Neglected but Rich Source of Information Supporting the Transition to Higher Quality Health Systems in Low and Middle Income Countries.” BMC Medicine 16 (1). https://doi.org/10.1186/s12916-018-1024-8.

- Hoffmann JA, Attridge MM, Carroll MS, Simon NE, Beck AF, Alpern ER. Association of Youth Suicides and County-Level Mental Health Professional Shortage Areas in the US. JAMA Pediatr. 2023 Jan 1;177(1):71-80. doi: 10.1001/jamapediatrics.2022.4419. PMID: 36409484; PMCID: PMC9679958.

- “Hipaa Privacy Rule Booklet.” n.d. https://privacyruleandresearch.nih.gov/pdf/HIPAA_Privacy_Rule_Booklet.pdf.

- Johnson, Hans, Eric McGhee, and Marisol Cuellar Mejia. “California’s Population.” Public Policy Institute of California, January 2022. https://www.ppic.org/publication/californias-population/.

- Porcel-Gálvez, Ana María, Sergio Barrientos-Trigo, Eugenia Gil-García, Olivia Aguilera-Castillo, Antonio Juan Pérez-Fernández, and Elena Fernández-García. 2020. “Factors Associated with In-Hospital Mortality in Acute Care Hospital Settings: A Prospective Observational Study.” International Journal of Environmental Research and Public Health 17 (21): 7951. https://doi.org/10.3390/ijerph17217951.

- Nass, Sharyl J, Laura A Levit, and Lawrence O Gostin. “The Value and Importance of Health Information Privacy.” Nih.gov. National Academies Press (US), 2019. https://www.ncbi.nlm.nih.gov/books/NBK9579/.

- Norori, Natalia, Qiyang Hu, Florence Marcelle Aellen, Francesca Dalia Faraci, and Athina Tzovara. “Addressing Bias in Big Data and AI for Health Care: A Call for Open Science.” Patterns 2, no. 10 (October 8, 2021): 100347. https://doi.org/10.1016/j.patter.2021.100347.

- “Trends in Inpatient Hospital Deaths: National Hospital Discharge Survey, 2000–2010 .” 2019. CDC. 2019. https://www.cdc.gov/nchs/products/databriefs/db118.htm.


