---
bibliography: references.bib
---

Managing health-related data and models comes with a wide variety of serious ethical concerns. Understanding the risks of biased data or an inaccurate model is critical to safeguarding against these. As such, as we work on these models, we must keep in mind the privacy of patients, the quality of our data, and its ability to accurately represent the demographics of the whole population, and we must be mindful of the variables that are included or excluded.

1)  Managing data: Collecting medical data is a delicate challenge. First and foremost, health data is personal and sensitive. It must be handled with the utmost respect and caution as it contains sensitive and personal information. The US legal system, through The Health Insurance Portability and Accountability Act of 1996 (HIPAA), protects sensitive patient information. However, to study the health system and understand the weaknesses and strengths of the current hospital system, we need data. As such, as data scientists, we must be sure to handle data in a careful manner that ensures that individual and identifiable information is not connected with the data used to build the model. Protecting privacy creates challenges in collecting the data and ensuring that the data is representative. ([NIH](https://www.ncbi.nlm.nih.gov/books/NBK9579/))

2)  Biases and Representation: Medical data must be representative of the population it is measuring or we risk creating an inaccurate and harmful model. Inaccurate data can reinforce stereotypes leading to misdiagnosis and mistreatment. Medical data differs from other data sources because inaccuracies are often a matter of life and death. In this particular set of models, we need to be cautious about the demographics and our ability to generalize the results. For example, this data gives good insight into California's hospital system, however, California is not representative of the nation. California's median age (37.9) is the eleventh youngest in the nation and almost a year younger than the median age nationally (38.8). Further, California is more diverse than other states and has a larger population of immigrants (27%) compared to the rest of the country (12%) ([PPIC](https://www.ppic.org/publication/californias-population/)). Further, the median income in California is more than \$15,000 greater than the national median income ([US Data](https://datausa.io/profile/geo/california?compare=united-states)). These are a couple of examples where California's data does not represent the greater US. It is important to note these disparities and study how they might impact the data and prevent us from generalizing our data to other hospital systems. ([NIH](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8515002/))

3)  Inclusion of Variables: In each model, we had to select which variables to include and which to exclude. For example, in the multiple linear regression models, `hispanic` was the only race variable that was significant in the full model and thus was included in the reduced model while others were not. This choice, even based on the data, is one that can impact the outcome. Transparency in which variables are included in the final models is critical to the reproducibility of the model and the preventing harmful biases. 

Conversely, good data and strong models can serve as guidance to hospitals and be accountability measures. For example, the NIH has found a 10% increase in in-hospital mortality rates due to unsafe practices while increased staffing is correlated with a 12% decrease in deaths. Accurate data reporting can provide accountability for hospital practices. This gives community members insight into the medical system and the needed improvements in their locality.

Further, better public policy can stem from accurate reporting. For example, when considering our models, overlaying deaths and demographic information can highlight at-risk groups that need further support. We find in our LASSO analysis that patients over the age of 55 are at a higher risk of death. As such, policymakers know that they need to further focus on resources for this community. Continued monitoring of the death rate can demonstrate if policy changes yield a change in mortality rates. Good policy is based on good data and models.
