---
bibliography: references.bib
---

In this paper, we dive into California's medical system. Almost 40 million people call California home, as such understanding the efficacy of the California hospital system proves relevant. In this study, we seek to gain a better understanding of the factors that are associated with in-patient deaths in the CA hospital system. Increased staffing, according to the NIH, is associated with decreased levels of in-patient death. Based on this concept, we want to investigate other demographic and economic factors that may be impacting in-patient health. 

To start, we completed a series of three regression analyses. In this analysis we want to know if we can predict in-patient deaths due to heart disease per thousand people. We start with a multiple linear regression that provides an unsatisfactory model with only two significant predictor variables. Next, we completed a LASSO regression which yielded insight into how the median income and age of the population impact deaths due to heart disease. The final regression model, a random forest model, reinforces the results from our other models. Through all three models, the number of cases of heart disease and the hospital rating are the most prevalent predictors. Age also continues to be a relevant variable with the population over the age of 55 most at risk. Based on weighting the importance of providing a detailed and robust model with the costs of adding additional variables and the risk of over fitting the data, we recommend using the random forest model. 

Next, we turn to a slightly different question regarding the CA hospital system. We complete three classification analyses to try to identify hospitals in Health Professional Shortage Areas (HPSA) based on demographics and geographic location details. To start, we conducted a K-fold model which produced a reduced model based on geographic and population factors. Next, we created a Tree model for the classification where we recommend the usage of the pruned tree. Finally, we used a boost model that produced similar results to the K-fold model. In the end, we recommend XXXX model. 

Through this analysis, we gain insight into the California hospital system. We aim to build prediction models for both heart disease in-patient deaths and Health Professional Shortage Areas. HPSA is associated with higher mortality rates of in-patients and thus understanding outcomes in the hospital as well as staffing together provides a broader picture of California hospitals.  