---
bibliography: references.bib
---

The best regression model found to predict the death rate due to heart disease with these data was the random forest model. It provides the lowest MSE value of 0.02992 while still explaining more than 80% of the variation in the model, and demonstrated a reasonable balance between bias and flexibility. To decrease prediction error, we found we had to sacrifice some of the power of the model: for example, the best multiple linear regression model explained over 90% of the variance, however, because we are handling medical data, accurate predictions are of the utmost importance. All three models demonstrate the importance of including the number of cases of heart disease as a predictor of the number of deaths. After controlling for heart disease cases, the next more significant factor was found to be hospital ranking, then the number of hospitals in a region. Demographic variable associations with heart disease deaths were weak or absent, which was surprising to the researchers and would be a good opportunity for further research. Understanding why demographic variables were not significant, which was an assumption of the research team, would be pressing for future medical studies, as well as collecting complete data, exploring other model diseases, and employing missing data handling methods (such as multiple imputation) for an accurate survey of the state of public health in California. 

For the classification model we found the cross validated boosting model with a shrinkage parameter to efficiently predict health professional service area status compared to other models. Other models including pruned and unpruned decision trees and reduced and full logistic regression performed well but the cross validated boosting model with a shrinkage parameter found a balance between having high accuracy 0.877551 and low mean prediction 0.122449 error rate compared to the logistic regression and decision tree models. All six model specifications reported hpsa score and hpsa designation population as important determinants of hpsa status with the final boosting model including metropolitan indicator as key in determining hpsa status. Demographic characteristics of the counties in which the hpsa's are located were initially considered. However after data cleaning didn't fit into our model specifications and were subsequently discarded.