<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression Analysis: Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="RegMethod_1_files/libs/clipboard/clipboard.min.js"></script>
<script src="RegMethod_1_files/libs/quarto-html/quarto.js"></script>
<script src="RegMethod_1_files/libs/quarto-html/popper.min.js"></script>
<script src="RegMethod_1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="RegMethod_1_files/libs/quarto-html/anchor.min.js"></script>
<link href="RegMethod_1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="RegMethod_1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="RegMethod_1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="RegMethod_1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="RegMethod_1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Analysis: Linear Models</h1>
<p class="subtitle lead">Name:Elise Buellesbach Course: STAT 427</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Here we are working on a basic multiple linear model with cross validation.</p>
<p>Question: Can mortality rate from heart disease per 1000 people be predicted from demographic conditions within counties in California?</p>
<p>To start, we will employ a series of multiple regressions to get a better understanding of the relationships at play and which variables are most useful in predicting the mortality rate from heart disease.</p>
<p>I begin by importing and setting up the data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse); <span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>reg_data_long <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">".</span><span class="sc">\\</span><span class="st">..</span><span class="sc">\\</span><span class="st">..</span><span class="sc">\\</span><span class="st">Data</span><span class="sc">\\</span><span class="st">reg_data_long.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 99 Columns: 40
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): County, Rating
dbl (38): TotalPop, MalePop, FemalePop, MedianAge, MaleMedianAge, FemaleMedi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># head(reg_data_long)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>reg_data_long<span class="sc">$</span>female_prop <span class="ot">&lt;-</span> reg_data_long<span class="sc">$</span>FemalePop<span class="sc">/</span>reg_data_long<span class="sc">$</span>TotalPop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>When I initially began building this model, I ran into issues in calculating the MSE because of a couple of NA values. To prevent this issue, I checked the data for NA values. Both PercFemale and PercUnder18yo have NA values and were thus removed from the full regression model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>na_counts <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(reg_data_long))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>na_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         County        TotalPop         MalePop       FemalePop       MedianAge 
              0               0               0               0               0 
  MaleMedianAge FemaleMedianAge     Under5yoPop    Under18yoPop   Pop21andOlder 
              0               0               0               0               0 
  Pop55andOlder   Pop60andOlder   Pop65andOlder      PercFemale   PercUnder18yo 
              0               0               0              12              12 
      num_desig     amer_indian           black        hispanic           asian 
              0               0               0               0               0 
     multi_race      pac_island           white         poverty     labor_force 
              0               0               0               0               0 
     unemployed   median_income     TotalDeaths      TotalCases       prop_hpsa 
              0               0               0               0               0 
  nonwhite_prop          Rating          Deaths   DeathsperThou     unempl_prop 
              0               0               0               0               0 
   poverty_prop     prop55older           Cases      HospNumber    CasesperThou 
              0               0               0               0               0 
    female_prop 
              0 </code></pre>
</div>
</div>
<p>Splitting up the data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>training_pct <span class="ot">&lt;-</span> .<span class="dv">8</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(reg_data_long), <span class="fu">floor</span>(training_pct<span class="sc">*</span><span class="fu">nrow</span>(reg_data_long)))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> reg_data_long[Z,]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79 41</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> reg_data_long[<span class="sc">-</span>Z,]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20 41</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>County <span class="ot">&lt;-</span> <span class="fu">factor</span>(test<span class="sc">$</span>County, <span class="at">levels =</span> <span class="fu">levels</span>(train<span class="sc">$</span>County))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="full-model" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Full Model</h1>
<p>Training the full model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(DeathsperThou <span class="sc">~</span> TotalPop <span class="sc">+</span> MalePop <span class="sc">+</span> FemalePop <span class="sc">+</span> MedianAge <span class="sc">+</span> MaleMedianAge <span class="sc">+</span> FemaleMedianAge <span class="sc">+</span> Under5yoPop <span class="sc">+</span> Under18yoPop <span class="sc">+</span> Pop21andOlder <span class="sc">+</span> Pop55andOlder <span class="sc">+</span> Pop60andOlder <span class="sc">+</span> Pop65andOlder <span class="sc">+</span> num_desig <span class="sc">+</span> amer_indian <span class="sc">+</span> black <span class="sc">+</span> hispanic <span class="sc">+</span> asian <span class="sc">+</span> multi_race <span class="sc">+</span> pac_island <span class="sc">+</span> white <span class="sc">+</span> poverty <span class="sc">+</span> labor_force <span class="sc">+</span> unemployed <span class="sc">+</span> median_income <span class="sc">+</span> TotalDeaths <span class="sc">+</span> TotalCases <span class="sc">+</span> prop_hpsa <span class="sc">+</span> nonwhite_prop <span class="sc">+</span> Rating <span class="sc">+</span> Deaths <span class="sc">+</span> unempl_prop <span class="sc">+</span> poverty_prop <span class="sc">+</span> prop55older <span class="sc">+</span> Cases <span class="sc">+</span> HospNumber <span class="sc">+</span> CasesperThou <span class="sc">+</span> female_prop , <span class="at">data =</span> train)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DeathsperThou ~ TotalPop + MalePop + FemalePop + 
    MedianAge + MaleMedianAge + FemaleMedianAge + Under5yoPop + 
    Under18yoPop + Pop21andOlder + Pop55andOlder + Pop60andOlder + 
    Pop65andOlder + num_desig + amer_indian + black + hispanic + 
    asian + multi_race + pac_island + white + poverty + labor_force + 
    unemployed + median_income + TotalDeaths + TotalCases + prop_hpsa + 
    nonwhite_prop + Rating + Deaths + unempl_prop + poverty_prop + 
    prop55older + Cases + HospNumber + CasesperThou + female_prop, 
    data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.26702 -0.02710  0.00018  0.02693  0.38361 

Coefficients: (1 not defined because of singularities)
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.476e+01  9.677e+00   1.525  0.13482    
TotalPop        -5.931e-05  3.533e-05  -1.679  0.10079    
MalePop         -3.238e-05  2.615e-05  -1.238  0.22266    
FemalePop               NA         NA      NA       NA    
MedianAge        3.873e-01  2.140e-01   1.810  0.07769 .  
MaleMedianAge   -3.582e-01  1.234e-01  -2.904  0.00592 ** 
FemaleMedianAge -4.030e-01  1.508e-01  -2.672  0.01076 *  
Under5yoPop     -4.857e-05  7.834e-05  -0.620  0.53872    
Under18yoPop     8.693e-05  5.331e-05   1.631  0.11062    
Pop21andOlder    9.340e-05  5.649e-05   1.653  0.10588    
Pop55andOlder   -6.930e-05  6.245e-05  -1.110  0.27362    
Pop60andOlder    1.896e-05  1.107e-04   0.171  0.86482    
Pop65andOlder    4.339e-05  7.970e-05   0.544  0.58910    
num_desig       -2.381e-03  2.080e-03  -1.145  0.25892    
amer_indian      7.318e-06  3.708e-05   0.197  0.84453    
black           -6.558e-06  9.342e-06  -0.702  0.48668    
hispanic         8.807e-06  5.090e-06   1.730  0.09115 .  
asian            4.462e-06  4.295e-06   1.039  0.30494    
multi_race       6.853e-05  5.490e-05   1.248  0.21902    
pac_island      -2.130e-05  6.064e-05  -0.351  0.72719    
white            1.295e-06  4.764e-06   0.272  0.78711    
poverty          5.334e-06  5.782e-06   0.922  0.36167    
labor_force     -1.302e-05  8.837e-06  -1.474  0.14815    
unemployed      -1.713e-05  1.891e-05  -0.906  0.37047    
median_income    2.027e-05  1.331e-05   1.523  0.13534    
TotalDeaths     -2.665e-04  9.168e-04  -0.291  0.77275    
TotalCases      -5.199e-05  1.883e-05  -2.761  0.00858 ** 
prop_hpsa       -2.052e-02  2.950e-01  -0.070  0.94489    
nonwhite_prop   -1.694e+00  1.696e+00  -0.999  0.32367    
RatingBetter    -1.170e-01  1.015e-01  -1.153  0.25571    
RatingWorse     -4.386e-02  1.007e-01  -0.436  0.66537    
Deaths           2.238e-04  1.519e-04   1.473  0.14839    
unempl_prop      4.769e+00  4.009e+00   1.190  0.24105    
poverty_prop    -4.411e+00  6.737e+00  -0.655  0.51629    
prop55older      2.768e+01  1.998e+01   1.386  0.17337    
Cases           -3.037e-06  3.359e-06  -0.904  0.37129    
HospNumber      -2.326e-04  1.308e-04  -1.778  0.08275 .  
CasesperThou     3.264e-02  3.848e-03   8.482 1.46e-10 ***
female_prop     -1.737e+01  1.094e+01  -1.587  0.12011    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.102 on 41 degrees of freedom
Multiple R-squared:  0.9655,    Adjusted R-squared:  0.9345 
F-statistic: 31.06 on 37 and 41 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(full_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced
Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These plots give some insight to the shape of the model. For example, the plotting on the QQ-plot does not demonstrate a strong linear relationship. The edges of the plot deviate from the line suggesting that the model is not perfectly linear. Further, the scattered dots on the Leverage plot show several points on the line of Cook’s Distance signifying that they have overstated influence on the model. With these concerns in mind, I want to investigate the linearity of the model further. Does a linear model make sense? To get a better understanding of the data, I created some basic plots to demonstrate the shape of the data and get an idea of if a linear model will make sense here (<a href="https://www.statology.org/plot-multiple-linear-regression-in-r/">source on code</a>)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(full_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear
Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lsfit(mod.mat[, -var], cbind(mod.mat[, var], response), wt = wt, :
'X' matrix was collinear</code></pre>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-5-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we can see that some variables provide a better linear fit than others. For example, variables such as <code>MaleMedianAge</code> and <code>FemaleMedianAge</code> both are more or less scattered along the regression line. However, other variables such as <code>MalePop</code> and <code>FemalePop</code> do not fit the line well. Instead, the data is gathered in one spot and has almost no linear shape. These graphs give some reason for concern that the basic full model will not be the strongest. Not all of the variables are linear so a reduced model might be a better fit.</p>
<p>However, to confirm these concerns, we will go ahead and calculate the Mean Square Error of the full model.</p>
<p>Testing the full model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(full_model, <span class="at">newdata =</span> test)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>mse <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>DeathsperThou <span class="sc">-</span> Yhat)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>mse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07419842</code></pre>
</div>
</div>
<p>The MSE is .0742. This is a low MSE in general. Next, we can see how a reduced model will work.</p>
<p>Here, I will take only the significant variables from the above model for the reduced model. This includes variables that are significant up to the p=.1 threshold This was chosen because so few variables are significant and I want to see what this model will yield. Then, we can remove more variables if the results warrant that action.</p>
</section>
<section id="reduced-model" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Reduced Model</h1>
<p>Training the reduced model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>reduced_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(DeathsperThou <span class="sc">~</span> MedianAge <span class="sc">+</span> MaleMedianAge <span class="sc">+</span> FemaleMedianAge <span class="sc">+</span> hispanic <span class="sc">+</span> CasesperThou <span class="sc">+</span> TotalCases <span class="sc">+</span> HospNumber, <span class="at">data =</span> train)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DeathsperThou ~ MedianAge + MaleMedianAge + FemaleMedianAge + 
    hispanic + CasesperThou + TotalCases + HospNumber, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.40557 -0.05661 -0.01361  0.05143  0.56690 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -1.900e-01  1.517e-01  -1.252   0.2146    
MedianAge        2.057e-01  1.394e-01   1.476   0.1443    
MaleMedianAge   -1.208e-01  7.612e-02  -1.588   0.1168    
FemaleMedianAge -8.090e-02  6.746e-02  -1.199   0.2344    
hispanic         3.747e-08  8.951e-08   0.419   0.6768    
CasesperThou     3.500e-02  1.482e-03  23.615   &lt;2e-16 ***
TotalCases      -6.504e-07  1.326e-06  -0.491   0.6253    
HospNumber      -1.122e-04  4.518e-05  -2.483   0.0154 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1192 on 71 degrees of freedom
Multiple R-squared:  0.9185,    Adjusted R-squared:  0.9104 
F-statistic: 114.3 on 7 and 71 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(reduced_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="RegMethod_1_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These plots of the reduced model yield the same concerns as the plots on the full model.</p>
<p>Testing the reduced model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>prediction_reduced <span class="ot">&lt;-</span> <span class="fu">predict</span>(reduced_model, <span class="at">newdata =</span> test)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mse_reduced <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>DeathsperThou <span class="sc">-</span> prediction_reduced)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>mse_reduced</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05392615</code></pre>
</div>
</div>
<p>However, we see a lower MSE at 0.0539 compared to 0.0742 from the full model. However, <code>hispanic</code>, <code>MedianAge</code>, <code>MaleMedianAge</code>, <code>FemaleMedianAge</code>, and <code>TotalCases</code> are no longer significant in this model.</p>
<p>To get an even better understanding of the data, we reduce the model again to just the signifant variables in the reduced model. We are down to just two predictor variables, <code>CasesperThou</code> and <code>HospNumber</code>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>small_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(DeathsperThou <span class="sc">~</span> CasesperThou <span class="sc">+</span> HospNumber, <span class="at">data=</span>train)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(small_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DeathsperThou ~ CasesperThou + HospNumber, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42998 -0.05724 -0.00882  0.02736  0.69795 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   9.317e-03  1.768e-02   0.527  0.59983    
CasesperThou  3.503e-02  1.451e-03  24.140  &lt; 2e-16 ***
HospNumber   -1.230e-04  4.346e-05  -2.830  0.00595 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.122 on 76 degrees of freedom
Multiple R-squared:  0.9087,    Adjusted R-squared:  0.9063 
F-statistic: 378.1 on 2 and 76 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>prediction_small <span class="ot">&lt;-</span> <span class="fu">predict</span>(small_model, <span class="at">newdata =</span> test)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>mse_small <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>DeathsperThou <span class="sc">-</span> prediction_reduced)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>mse_small</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05392615</code></pre>
</div>
</div>
<p>This small model yields the same MSE as the previous reduced model of 0.0539 and only requires two variables.</p>
</section>
<section id="comparison-between-the-two-models-and-recommendation" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Comparison Between the Two Models and Recommendation</h1>
<p>Between the original two models, the reduced model should be chosen. It offers a more accurate prediction of the rate of deaths due to heart disease per thousand people. The reduced model uses only 7 prediction variables compared to the more than 30 variables that the full model requires. Further, the smallest model with only 2 variables gives the same low MSE value with even fewer predictor variables. This implies that many of those variables are either not useful in prediction or they might have high levels of multi-co linearity This concept will be explored further in the next regression models.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>